export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import NextAuthProvider from 'context/NextAuthProvider';
import QueryClientProvider from 'context/QueryClientProvider';
import Layout from 'components/Layout';

import "./global.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link href="//cdn.jsdelivr.net/npm/mana-font@latest/css/mana.min.css" rel="stylesheet" type="text/css" />
      <body>
        <NextAuthProvider>
          <QueryClientProvider>
            <Layout>{children}</Layout>
          </QueryClientProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
